name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.19.2

    - name: Install dependencies (Specifically Ubuntu and Mac OS)
      run: make install_deps
    
    - name: Build Go Project
      run: make
      
    - name: GitHub Releases
      # You may pin to the exact commit or the version.
      # uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f
      uses: fnkr/github-action-ghr@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_PATH: bin/
